/*******************************************************************************
* FILE NAME: strgen.h                                                          *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     strgen- Sample of using IStringGenerator class                           *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_strgen
#define WND_strgen  VBBASEWINDOWID
#endif

#define WNDOFFSET_strgen_FrameWindow  0
#define WND_strgen_FrameWindow  WND_strgen

#define WND_strgen_Canvas  IC_FRAME_CLIENT_ID

#define WNDOFFSET_strgen_CollectionViewListBox1  1
#define WND_strgen_CollectionViewListBox1  WND_strgen + WNDOFFSET_strgen_CollectionViewListBox1

#define WNDOFFSET_strgen_StaticText1  2
#define WND_strgen_StaticText1  WND_strgen + WNDOFFSET_strgen_StaticText1





